### ISSUE TITLE
the file_name '/tmp/sensu-plugins-http/bin/check-http.rb' does not exist, or is not readable

### ISSUE THREAD

**Issue by 030** [030/ansible-sensu#12]
```
- name: be sure check-http.rb is copied
  copy:
    src: /tmp/sensu-plugins-http/bin/check-http.rb
    dest: /tmp/check-http.rb
    owner: sensu
    group: sensu
    mode: 0500
    remote_src: true
```
